### ISSUE TITLE
error while running catkin_make on setup.md

### ISSUE THREAD

**Issue by haliliceylan** [micss-lab/AAMA-sim#12]
![image](https://github.com/micss-lab/AAMA-sim/assets/33789758/a7389f7f-8cc8-4c28-8bed-eb827d6af461)

at this [section](https://github.com/micss-lab/AAMA-sim/blob/main/setup.md#create-catkin_ws), while following instructions. I faced above problem.

System Info:
```
halil@halil-OptiPlex-7020:~/catkin_ws$ uname -a
Linux halil-OptiPlex-7020 5.15.0-73-generic #80~20.04.1-Ubuntu SMP Wed May 17 14:58:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
halil@halil-OptiPlex-7020:~/catkin_ws$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

**Comment by DogukanAltay** [comment]
I will update readme accordingly.

**Comment by haliliceylan** [comment]
yes it worked !
